#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_44(
      KC_Q, KC_W, KC_E, KC_R, KC_T, KC_NO,                                           KC_NO, KC_Y, KC_U, KC_I, KC_O, KC_P,
      KC_A, KC_S, KC_D, KC_F, KC_G, KC_NO,                                           KC_NO, KC_H, KC_J, KC_K, KC_L, LCTL_T(KC_SCLN),
      LSFT_T(KC_Z), KC_X, KC_C, KC_V, KC_B, KC_NO,                                   KC_NO, KC_N, KC_M, KC_COMM, KC_DOT, MT(MOD_LSFT,KC_SLSH),
      MO(2), LCTL_T(KC_CAPS), LT(1,KC_GRV), LGUI_T(KC_TAB), LALT_T(KC_BSPC), KC_ESC, LALT_T(KC_ENT), LGUI_T(KC_SPC), OSL(1), KC_NO, KC_NO, KC_NO
  )

};

